[package]
name = "sweat"
version = "0.1.0"
authors = []
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
near-sdk = "4.0.0-pre.7"
near-contract-standards = "4.0.0-pre.7"
static_assertions = "1.1.0"